version: '3.9'
services:
  host:
    build:
      context: .
      target: host
    image: host
    container_name: host
    ports:
      - '9000:80'
    networks:
      - app-network

  navi:
    build:
      context: .
      target: navi
    image: navi
    container_name: navi
    networks:
      - app-network

  rinex-to-csv:
    build:
      context: .
      target: rinex-to-csv
    image: rinex-to-csv
    container_name: rinex-to-csv
    networks:
      - app-network

  gecrec:
    build:
      context: .
      target: gecrec
    image: gecrec
    container_name: gecrec
    networks:
      - app-network

networks:
  app-network:
